### ISSUE TITLE
Issue deploying chart: /opt/interlink/token missing

### ISSUE THREAD

**Issue by vitcozzolino** [interlink-hq/interlink-helm-chart#21]
Hi, I have deployed the latest version of interlink using the Helm chart but I see the following error:

<img width="1422" alt="Image" src="https://github.com/user-attachments/assets/ae0f2213-efa4-48e0-9cad-ba80c62ef5a0" />

In the documentation, I can't find information about what to put under `/opt/interlink`.

On the edge side, I have completed the installation following this tutorial https://interlink-hq.github.io/interLink/docs/cookbook/edge

**Comment by dciangot** [comment]
@vitcozzolino can you share the helm values yaml file (with secrets omitted) here? 
Looks like the token returned by Keycloak is showing a different issuer w.r.t. the one expected by the refresh script.

**Comment by vcozzolino** [comment]
Here is the relevant part of my deployment:

```
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: NODENAME
          value: cn04
        - name: KUBELET_PORT
          value: "10250"
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: CONFIGPATH
          value: /etc/interlink/InterLinkConfig.yaml
        - name: VKTOKENFILE
          value: /opt/interlink/token
        image: ghcr.io/interlink-hq/interlink/virtual-kubelet-inttw:latest
        imagePullPolicy: Always
        name: vk
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/interlink/InterLinkConfig.yaml
          name: config
          subPath: InterLinkConfig.yaml
        - mountPath: /opt/interlink
          name: token
      - command:
        - python3
        - /opt/refresh.py
        env:
        - name: IAM_USER_ID
          value: interlink-cn04
        - name: IAM_TOKEN_ENDPOINT
          value: http://192.168.23.11:31786/realms/DECICE/protocol/openid-connect/token
        - name: IAM_CLIENT_ID
          value: interlink
        - name: IAM_CLIENT_SECRET
          value: xxxx
        - name: IAM_REFRESH_TOKEN
          value: eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyMzdlMWJiYS04Mzk4LTQ4Y2ItODQ2MC1iNGJkOWNjNjlmZDcifQ.eyJpYXQiOjE3NDY0MzcyOTAsImp0aSI6ImI4NWEzOGQxLWVhMWMtNDcxNi04ZWUyLTAxYTUyYmE3NTFmNSIsImlzcyI6Imh0dHBzOi8vMTQxLjIuMTEyLjE3OjMxNzg0L3JlYWxtcy9ERUNJQ0UiLCJhdWQiOiJodHRwczovLzE0MS4yLjExMi4xNzozMTc4NC9yZWFsbXMvREVDSUNFIiwic3ViIjoiMmUwMzQ5MzAtODE4Ni00NzBiLTg5ZTQtZmNkMThkZTcyNmEwIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6ImludGVybGluay1hcHAiLCJzZXNzaW9uX3N0YXRlIjoiN2MzOTU5YzctZTJiMy00NDZlLThhZGQtZWFhNzdkMmI4ZWRjIiwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSBvZmZsaW5lX2FjY2VzcyIsInNpZCI6IjdjMzk1OWM3LWUyYjMtNDQ2ZS04YWRkLWVhYTc3ZDJiOGVkYyJ9.E54Rg5lKwkyGqO3DtuB2zVe24XqiPVzbF4V5vG-cpjIzlVxkaMEZ3hNR4N-DpPuOGOVVSAi3ug6z5W1tJ4PHjw
        - name: IAM_VK_AUD
          value: interlink
        - name: IAM_GRANT_TYPE
          value: authorization_code
        - name: TOKEN_PATH
          value: /opt/interlink/token
        image: ghcr.io/interlink-hq/interlink/virtual-kubelet-inttw-refresh:latest
        imagePullPolicy: Always
        name: refresh-token
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/interlink
          name: token
```

In keycloak, I see this error messages:
```
2025-05-06 10:57:06,621 WARN  [org.keycloak.events] (executor-thread-110) type="REFRESH_TOKEN_ERROR", realmId="437a305a-6d02-4b18-a3b1-38b6e459f723", clientId="interlink", userId="null", ipAddress="10.233.65.1", error="invalid_token", grant_type="refresh_token", client_auth_method="client-secret"
```
